---
- name: play1
  hosts: host1
  become: true    ## sudo privilege run
  tasks:
    - name: Execute Command 'Date'
      command: date
    - name: Execute Script on server
      script: test_script.sh
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes
    - name: Install Nginx
      apt: name=nginx state=latest

#- name: play2
#  hosts: host2
#  sudo: yes
#  tasks:
#    - name: Execute script on server
#      script: test_script.sh
#    - name: Install Nginx
#      apt: name=nginx state=latest